EVENT_TYPES = %w[
  ACCOUNT.CREATED
  ACCOUNT.UPDATED
  ACH.INCOMING.FUTURE_DATED
  APPLICATION.CREATED
  APPLICATION.UPDATED
  BUSINESS.CREATED
  BUSINESS.UPDATED
  BUSINESS.VERIFICATION_OUTCOME.UPDATED
  CARD.CREATED
  CARD.DIGITALWALLETTOKEN.CREATED
  CARD.DIGITALWALLETTOKEN.UPDATED
  CARD.IMAGE.UPDATED
  CARD.UPDATED
  CASE.CREATED
  CASE.UPDATED
  CASH_PICKUP.CREATED
  CASH_PICKUP.UPDATED
  CREDIT_SCORE.CREATED
  CUSTOMER.CREATED
  CUSTOMER.KYC_OUTCOME.UPDATED
  CUSTOMER.UPDATED
  EXTERNAL_CARD.CREATED
  EXTERNAL_CARD.DELETED
  EXTERNAL_CARD.UPDATED
  EXTERNAL_CARD_TRANSFER.CREATED
  EXTERNAL_CARD_TRANSFER.UPDATED
  INTEREST.MONTHLY_PAYOUT
  INTERNAL_ACCOUNT.CREATED
  INTERNAL_ACCOUNT.UPDATED
  INTERNAL_TRANSFER.SUCCEEDED
  NOTE.CREATED
  NOTE.UPDATED
  PAYMENT_SCHEDULE.CREATED
  PAYMENT_SCHEDULE.PAYMENT.CREATED
  PAYMENT_SCHEDULE.UPDATED
  PERSON.CREATED
  PERSON.UPDATED
  PERSON.VERIFICATION_OUTCOME.UPDATED
  STATEMENT.CREATED
  TRANSACTION.PENDING.CREATED
  TRANSACTION.PENDING.UPDATED
  TRANSACTION.POSTED.CREATED
  TRANSACTION.POSTED.UPDATED
].freeze

EVENT_WILDCARDS = %w[
  ACCOUNT.*
  ACH.*
  APPLICATION.*
  BUSINESS.*
  CARD.*
  CASE.*
  CASH_PICKUP.*
  CREDIT_SCORE.*
  CUSTOMER.*
  EXTERNAL_CARD.*
  EXTERNAL_CARD_TRANSFER.*
  INTEREST.*
  INTERNAL_TRANSFER.*
  NOTE.*
  PAYMENT_SCHEDULE.*
  PERSON.*
  STATEMENT.*
  TRANSACTION.*
].freeze

class Syncterrifier::Webhook < Syncterrifier::Model
  endpoint :webhooks

  required_params(
    # description: String,
    enabled_events: Array,
    is_enabled: Boolean,
    # metadata: String,
    url: String,
  )
end
